# elk/logstash/logstash.conf
input {
  beats {
    port => 5044
  }
  tcp {
    port => 5000
    codec => json
  }
  udp {
    port => 5000
    codec => json
  }
}

filter {
  if [service] == "ground-station-backend" {
    mutate {
      add_tag => [ "backend" ]
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "solvrex-telemetry-logs-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}
